# Generated by Django 3.1.1 on 2020-09-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menocare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, null=True)),
                ('client_phone', models.CharField(max_length=100, null=True)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_address', models.CharField(max_length=100, null=True)),
                ('appt_time', models.CharField(max_length=100, null=True)),
                ('appt_day', models.CharField(max_length=100, null=True)),
                ('client_msg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, null=True)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_msg', models.TextField()),
            ],
        ),
    ]
