# Generated by Django 3.1.1 on 2020-09-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menocare', '0003_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_on',
        ),
    ]
