# Generated by Django 3.1.1 on 2020-09-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menocare', '0005_auto_20200917_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=80)),
                ('content', models.TextField()),
                ('who', models.CharField(default='Dental Patient', max_length=80)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(default='default.jpg', upload_to='images')),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
