# Generated by Django 3.1.1 on 2020-09-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menocare', '0006_auto_20200919_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='MenoCare', max_length=200, null=True),
        ),
    ]
